// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr_zvPzk19MsZe7zpdydmHs7X_pC2ADvM',
    appId: '1:131573614015:web:1fa38ab1932d9a34c98d0a',
    messagingSenderId: '131573614015',
    projectId: 'spotify-eb229',
    authDomain: 'spotify-eb229.firebaseapp.com',
    storageBucket: 'spotify-eb229.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqZ8MsyadtzH9b8jfIZOEZcMa5yx4wTk',
    appId: '1:131573614015:android:1a5dd43051cf4705c98d0a',
    messagingSenderId: '131573614015',
    projectId: 'spotify-eb229',
    storageBucket: 'spotify-eb229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANf1TL9TmTLAU1zrYhZiTnrd23BOpnvDU',
    appId: '1:131573614015:ios:95c283298f33aba5c98d0a',
    messagingSenderId: '131573614015',
    projectId: 'spotify-eb229',
    storageBucket: 'spotify-eb229.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANf1TL9TmTLAU1zrYhZiTnrd23BOpnvDU',
    appId: '1:131573614015:ios:95c283298f33aba5c98d0a',
    messagingSenderId: '131573614015',
    projectId: 'spotify-eb229',
    storageBucket: 'spotify-eb229.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr_zvPzk19MsZe7zpdydmHs7X_pC2ADvM',
    appId: '1:131573614015:web:b047dbd174061653c98d0a',
    messagingSenderId: '131573614015',
    projectId: 'spotify-eb229',
    authDomain: 'spotify-eb229.firebaseapp.com',
    storageBucket: 'spotify-eb229.appspot.com',
  );
}
